version: '3'

services:
    postgres:
        restart: always
        image: postgres:latest
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5430:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes:
    pgdata:
